name: format

on:
  pull_request:
  push:
    branches:
      - main

jobs: 
  bank:
   runs-on: ubuntu-latest

   steps:
   - name: Checkout
     uses: actions/checkout@v3

   - name: Install yarn
     uses: yarn/action-setup@v2.2.2
     with:
        version: 7.x.x

   - name: Install Node.js
     uses: actions/setup-node@v3
     with:
      node-version: 18
  
   - name: Install deps
     run: yarn i

   - name: Run rome 
     run: yarn rome format --write .
