name: format

on:
  pull_request:
  push:
    branches:
      - main

jobs: 
  bank:
   runs-on: ubuntu-latest

   steps:
   - name: Checkout
     uses: actions/checkout@v3

      - name: Install apt-get
        run: |
        sudo apt-get update && sudo apt-get install -y apt-utils

     - name: Install npm
       run: |
         curl -sL https://deb.nodesource.com/setup_16.x | sudo bash -
         sudo apt-get install -y nodejs
         
   - name: Install Node.js
     uses: actions/setup-node@v3
     with:
      node-version: 18
  
   - name: Install deps
     run: npm i

   - name: Run rome 
     run: npm rome format --write .
