name: iOS

on:
  pull_request:
  push:
    branches:
      - main
  
      
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
     - name: Checkout repository
       uses: actions/checkout@v3
     
     - name: Install yarn
      uses: actions/checkout@v2
       run: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - && echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list && sudo apt-get update && sudo apt-get install yarn
       with:
        version: 7.x.x 

     - name: Install Node
       uses: actions/setup-node@v3
       with:
        node-version: 18
        cache: 'yarn'

     - name: Install dependencies
       run: yarn i
     
     - name: Start Expo server
       run: yarn ios
