name: iOS

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
     - name: Checkout repository
       uses: actions/checkout@v3
     
      - name: Install apt-get
        run: |
        sudo apt-get update && sudo apt-get install -y apt-utils

     - name: Install npm
       run: |
         curl -sL https://deb.nodesource.com/setup_16.x | sudo bash -
         sudo apt-get install -y nodejs

     - name: Install Node
       uses: actions/setup-node@v3
       with:
         node-version: 18
         cache: 'npm'

     - name: Install dependencies
       run: npm ci

     - name: Run rome
       run: npm run rome format --write .

     - name: Start Expo server
       run: npm run ios
