name: iOS

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
     - name: Checkout repository
       uses: actions/checkout@v3
     
     - name: Install npm
       uses: actions/npm@v3
       with:
         version: 7.x.x

     - name: Install Node
       uses: actions/setup-node@v3
       with:
         node-version: 18
         cache: 'npm'

     - name: Install dependencies
       run: npm ci
     
     - name: Start Expo server
       run: npm run ios
